{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "file-upload-service.serviceAccountName" . }}
  namespace: {{ include "file-upload-service.namespace" . }}
  labels:
    {{- include "file-upload-service.labels" . | nindent 4 }}
  {{- if or .Values.serviceAccount.annotations .Values.serviceAccount.iamRoleArn }}
  annotations:
    {{- if .Values.serviceAccount.iamRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.iamRoleArn | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- range $key, $value := . }}
    {{- if ne $key "eks.amazonaws.com/role-arn" }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}

